name: Trigger Netlify Build
on:
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes
jobs:
  build:
    name: Build on Netlify
    runs-on: ubuntu-latest
    steps:
      - name: Build on master
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5e9182efabd8cc11552857d1
