name: Trigger Netlify Build
on:
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes
jobs:
  build:
    name: Build on Netlify
    runs-on: ubuntu-latest
    steps:
      - name: Build on master
        env:
          NETLIFY_HOOK_URL: ${{ secrets.NETLIFY_HOOK_URL }}
        run: curl -X POST -d {} "$NETLIFY_HOOK_URL"
