name: Trigger Netlify Build
on:
  schedule:
    # Every 5 minutes
    - cron: '*/5 * * * *'
jobs:
  build:
    name: Build on netlify
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_HOOK_URL }}
